#' name_mapping
#'
#' @description A utils function
#'
#' @return The return value, if any, from executing the utility.
#'
#' @noRd

mapping_spatial <- c(
  REGION = "REGION",
  REGION = "REGIONS",
  REGION = "REGION NAME",
  REGION = "REGION_NAME",
  REGION = "REGION-NAME",
  SITE = "SITE",
  SITE = "SITES",
  SITE = "PLACE",
  LOCATION = "LOCATION",
  LOCATION = "LOC",
  SUB_REGION = "SUBREGION",
  SUB_REGION = "SUB REGION",
  SUB_REGION = "SUB-REGION",
  SUB_REGION = "SUB_REGION",
  SUB_REGION = "SUB REGION NAME",
  SUB_REGION = "SUB_REGION_NAME",
  SUB_REGION = "SUB-REGION-NAME",
  SUB_REGION = "SUB.REGION.NAME",
  SUB_REGION = "SUBREGIONNAME",
  SITE = "STATION",
  HABITAT = "HABITAT"
)

mapping_coordinates <- c(
  LAT_DEGREES = "LAT_DEGREES",
  LAT_DEGREES = "LATITUDE",
  LAT_DEGREES = "LAT",
  LAT_DEGREES = "LTTD",
  LAT_DEGREES = "COORD_LAT",
  LAT_DEGREES = "LAT_COORD",
  LON_DEGREES = "LON_DEGREES",
  LON_DEGREES = "LONGITUDE",
  LON_DEGREES = "LON",
  LON_DEGREES = "LONG",
  LON_DEGREES = "COORD_LON",
  LON_DEGREES = "COORD_LONG",
  LON_DEGREES = "LON_COORD",
  LON_DEGREES = "LONG_COORD"
)

mapping_completed <- c(
  METERS_COMPLETED = "METERS_COMPLETED",
  METERS_COMPLETED = "METERS COMPLETED",
  METERS_COMPLETED = "METERS-COMPLETED",
  METERS_COMPLETED = "METERS.COMPLETED",
  METERS_COMPLETED = "METERS_COMPLETED_DEMO",
  METERS_COMPLETED = "METERS COMPLETED DEMO",
  METERS_COMPLETED = "METERS-COMPLETED-DEMO",
  METERS_COMPLETED = "METERS.COMPLETED.DEMO",
  METERS_COMPLETED = "METERS_DEMO",
  METERS_COMPLETED = "METERS DEMO",
  METERS_COMPLETED = "METERS-DEMO",
  METERS_COMPLETED = "METERS.DEMO",
  METERS_COMPLETED = "METERS_COMPLETED_LPI",
  METERS_COMPLETED = "METERS COMPLETED LPI",
  METERS_COMPLETED = "METERS-COMPLETED-LPI",
  METERS_COMPLETED = "METERS.COMPLETED.LPI",
  METERS_COMPLETED = "METERS_LPI",
  METERS_COMPLETED = "METERS LPI",
  METERS_COMPLETED = "METERS-LPI",
  METERS_COMPLETED = "METERS.LPI",
  METERS_COMPLETED = "METERS_COMPLETED_MOBILE",
  METERS_COMPLETED = "METERS COMPLETED MOBILE",
  METERS_COMPLETED = "METERS-COMPLETED-MOBILE",
  METERS_COMPLETED = "METERS.COMPLETED.MOBILE",
  METERS_COMPLETED = "METERS_MOBILE",
  METERS_COMPLETED = "METERS MOBILE",
  METERS_COMPLETED = "METERS-MOBILE",
  METERS_COMPLETED = "METERS.MOBILE",
  METERS_COMPLETED = "METERS",
  METERS_COMPLETED = "TRANSECT LENGTH",
  METERS_COMPLETED = "TRANSECT_LENGTH",
  METERS_COMPLETED = "TRANSECT-LENGTH"
)

mapping_species <- c(
  SPECIES_NAME = "SPECIES_NAME",
  SPECIES_NAME = "SPECIES NAME",
  SPECIES_NAME = "SPECIES.NAME",
  SPECIES_NAME = "SPECIES-NAME",
  SPECIES_NAME = "SPECIES",
  SPECIES_NAME = "NAMES",
  SPECIES_NAME = "SCIENTIFIC_NAME",
  SPECIES_NAME = "SCIENTIFIC NAME",
  SPECIES_NAME = "SCIENTIFIC-NAME",
  SPECIES_NAME = "SCIENTIFIC.NAME",
  SPECIES_NAME = "SCIENTIFIC_NAMES",
  SPECIES_NAME = "SCIENTIFIC NAMES",
  SPECIES_NAME = "SCIENTIFIC-NAMES",
  SPECIES_NAME = "SCIENTIFIC.NAMES"
)

mapping_transect <- c(
  PRIMARY_SAMPLE_UNIT = "PRIMARY_SAMPLE_UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY SAMPLE UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY.SAMPLE.UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY-SAMPLE-UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARYSAMPLEUNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY_SAMPLING_UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY SAMPLING UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY-SAMPLING-UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARY.SAMPLING.UNIT",
  PRIMARY_SAMPLE_UNIT = "PRIMARYSAMPLINGUNIT",
  PRIMARY_SAMPLE_UNIT = "TRANSECT",
  PRIMARY_SAMPLE_UNIT = "SAMPLE_UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLE UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLE-UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLE.UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLING_UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLING-UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLING UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLING.UNIT",
  PRIMARY_SAMPLE_UNIT = "SAMPLING",
  PRIMARY_SAMPLE_UNIT = "SAMPLE",
  PRIMARY_SAMPLE_UNIT = "SAMPLEU",
  PRIMARY_SAMPLE_UNIT = "UNIT",
  PRIMARY_SAMPLE_UNIT = "SPATIALUNIT",
  PRIMARY_SAMPLE_UNIT = "SPATIAL UNIT",
  PRIMARY_SAMPLE_UNIT = "SPATIAL-UNIT",
  PRIMARY_SAMPLE_UNIT = "SPATIAL_UNIT",
  PRIMARY_SAMPLE_UNIT = "SPATIAL.UNIT",
  PRIMARY_SAMPLE_UNIT = "TRANSECT_NAME",
  PRIMARY_SAMPLE_UNIT = "TRANSECT NAME",
  PRIMARY_SAMPLE_UNIT = "TRANSECT-NAME",
  PRIMARY_SAMPLE_UNIT = "TRANSECT.NAME",
  PRIMARY_SAMPLE_UNIT = "TRANSECT CODE",
  PRIMARY_SAMPLE_UNIT = "TRANSECT_CODE",
  PRIMARY_SAMPLE_UNIT = "TRANSECT-CODE",
  PRIMARY_SAMPLE_UNIT = "TRANSECT.CODE"
)
